### ISSUE TITLE
Undefined class or binding 'Spiral\Boot\EnvironmentInterface'

### ISSUE THREAD

**Issue by Noramarth** [spiral/framework#481]
```php
Undefined class or binding 'Spiral\Boot\EnvironmentInterface'
#0 [...]/vendor/spiral/framework/src/Boot/src/helpers.php(68): spiral()
#1 [...]/app/config/database.php(37): env()
```
Makes no sense at all but from what I can find: 
```EnvironmentInterface``` is not actually bound ?

composer.json:
```json
"require": {
    "php": ">=8.0",
    "ext-curl": "*",
    "ext-zip": "*",
    "cycle/annotated": "2.3.1",
    "cycle/migrations": "1.0.10",
    "cycle/orm": "1.4.2",
    "cycle/proxy-factory": "1.3.1",
    "doctrine/cache": "1.11.3",
    "firebase/php-jwt": "v5.4.0",
    "jetbrains/phpstorm-attributes": "1.0",
    "spiral/database": "2.8.4",
    "spiral/dotenv-bridge": "2.7.2",
    "spiral/framework": "2.8.7",
    "spiral/jobs": "2.2.1",
    "spiral/migrations": "2.2.0",
    "spiral/php-grpc": "1.5.0",
    "spiral/prototype": "2.7.2",
    "spiral/roadrunner": "1.9.2",
    "php-di/php-di": "^6.3.0",
    "grpc/grpc": "1.42.0"
  },
```

App.php only contains default values

**Comment by rustatian** [comment]
@Noramarth You have to wait for the RR2 support for the framework to migrate from the `php-grpc` (I guess). Or, if you don't use the spiral framework, you need to slightly update your worker (follow the https://roadrunner.dev/docs/integration-migration migration guide).
