### ISSUE TITLE
[spiral/tokenizer] FatalException During fetch Trait 

### ISSUE THREAD

**Issue by roxblnfk** [spiral/framework#824]
### Description

I have a lot of similar messages in Sentry:

```
Spiral\Exceptions\Exception\FatalException

During class fetch: Uncaught Spiral\Tokenizer\Exception\LocatorException: Class 'CliTube\Bridge\Spiral\Command\PaginationTrait' can not be loaded in /var/www/vendor/spiral/framework/src/Tokenizer/src/AbstractLocator.php:74
Stack trace:
#0 /var/www/app/src/Api/Cli/Command/Query/ListCommand.php(21): Spiral\Tokenizer\AbstractLocator::Spiral\Tokenizer\{closure}('CliTube\\Bridge\\...')
#1 /var/www/vendor/composer/ClassLoader.php(571): include('/var/www/app/sr...')
#2 /var/www/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/vendor...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Api\\Cli\\Com...')
#4 /var/www/vendor/spiral/framework/src/Tokenizer/src/AbstractLocator.php(83): ReflectionClass->__construct('App\\Api\\Cli\\Com...')
#5 /var/www/vendor/spiral/framework/src/Tokenizer/src/ClassLocator.php(25): Spiral\Tokenizer\AbstractLocator->classReflection('App\\Api\\Cli\\Com...')
#6 /var/www/vendor/spiral/framework/src/Tokenizer/src/Bootloader/TokenizerListenerBootloader.php(37): Spiral\Tokenizer\ClassLocator->getClasses()
#7 [internal function]: Spiral\Tokenizer\Bootloader\TokenizerListenerBootloader->Spiral\Tokenizer\Bootloader\{closure}(Object(Spiral\Tokenizer\ClassLocator))
#8 /var/www/vendor/spiral/framework/src/Core/src/Internal/Invoker.php(73): ReflectionFunction->invokeArgs(Array)
#9 /var/www/vendor/spiral/framework/src/Core/src/Container.php(210): Spiral\Core\Internal\Invoker->invoke(Object(Closure), Array)
#10 /var/www/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(299): Spiral\Core\Container->invoke(Object(Closure))
#11 /var/www/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(154): Spiral\Boot\AbstractKernel->fireCallbacks(Array)
#12 /var/www/vendor/spiral/framework/src/Core/src/ContainerScope.php(37): Spiral\Boot\AbstractKernel->Spiral\Boot\{closure}()
#13 /var/www/vendor/spiral/framework/src/Core/src/Container.php(158): Spiral\Core\ContainerScope::runScope(Object(Spiral\Core\Container), Object(Closure))
#14 /var/www/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(155): Spiral\Core\Container->runScope(Array, Object(Closure))
#15 /var/www/app.php(23): Spiral\Boot\AbstractKernel->run()
#16 {main}

```

### How To Reproduce

Create console command with the trait https://github.com/clitube/bridge-spiral/blob/master/src/Command/PaginationTrait.php
Run tokenizer

### Additional Info

| Q                   | A
| ------------------- | ---
| Framework Version   | 3.1.0 
| PHP version         | 8.1 
| Operating system    | Linux

**Comment by butschster** [comment]
Hello @roxblnfk!

Thank you for the issue! In the last releases we fixed a problem. Could you check if the problem is actual? I could not reproduce it in the last 3.6.0 release.
